apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dev-consul.fullname" . }}
  labels:
    {{- include "dev-consul.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "dev-consul.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dev-consul.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8500
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /v1/status/leader
              port: http
          readinessProbe:
            httpGet:
              path: /v1/status/leader
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /consul/config
            - name: data
              mountPath: /consul/data
      volumes:
        - name: config
          configMap:
            name: {{ include "dev-consul.fullname" . }}
        - name: data
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
